import json
import os

notebook_path = "/Users/omidshojaeianzanjani/Documents/uni/AdvanceStatisticsLearning/Module A/projects/Assignment2/04 LAB_A Reinforce.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

for cell in nb['cells']:
    if cell['cell_type'] == 'code':
        source = ''.join(cell['source'])
        if 'def show_video(env_name):' in source:
            new_source = []
            for line in source.split('\n'):
                if "mp4 = 'video/{}.mp4'.format(env_name)" in line:
                    new_source.append("        # Find the actual file generated by the recorder")
                    new_source.append("        matching_files = [m for m in mp4list if env_name in m]")
                    new_source.append("        mp4 = matching_files[0] if matching_files else mp4list[0]")
                else:
                    new_source.append(line)
            cell['source'] = [line + '\n' for line in new_source[:-1]]
            break

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)
print("Notebook video cell fixed.")
